// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log

import (
	"honey_server/api/log"
)

type ControllerV1 struct{}

func NewV1() log.ILogV1 {
	return &ControllerV1{}
}
