// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package honey

import (
	"honey_server/api/honey"
)

type ControllerV1 struct{}

func NewV1() honey.IHoneyV1 {
	return &ControllerV1{}
}
