// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package net

import (
	"honey_server/api/net"
)

type ControllerV1 struct{}

func NewV1() net.INetV1 {
	return &ControllerV1{}
}
