// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package host

import (
	"honey_server/api/host"
)

type ControllerV1 struct{}

func NewV1() host.IHostV1 {
	return &ControllerV1{}
}
