// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package captcha

import (
	"honey_server/api/captcha"
)

type ControllerV1 struct{}

func NewV1() captcha.ICaptchaV1 {
	return &ControllerV1{}
}
